dist: trusty
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
